version: "3.7"
volumes:
    data:
        name: data

services: 
    backend:
        image: node:12.16.1-alpine
        volumes:
            - .:/ws
        ports:
            - 3000:3000
        working_dir: /ws/backend
        entrypoint: sh -c 'tail -f'
    
