version: "3.7"
volumes:
    data:
        name: data

services:

  db:
    image: postgres:9.6
    volumes:
    #Volume dos dados
    - data:/var/lib/postgresql/data
    - ./db-scripts/:/docker-entrypoint-initdb.d/
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  backend:
    image: node:12.16.1-alpine
    volumes:
    - .:/ws
    ports:
    - 3000:3000
    working_dir: /ws/backend
    entrypoint: sh -c 'apk add yarn;tail -f'
    
