version: "3.7"
volumes:
    data:
        name: data

services: 
    backend:
        image: node:13.8.0-alpine3.11
        volumes:
            - .:/ws
        ports:
            - 3000:3000
        working_dir: /ws/backend
        entrypoint: sh -c 'npm install;tail -f'
    
