version: "3.7"
volumes:
  data:
    name: data

services:
  db:
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql/data
      - ./db-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3000:3000
