version: "3.7"
volumes:
    data:
        name: data

services: 

  db:
    container_name: db
    image: postgres:9.6
    volumes:
    #Volume dos dados
    - dados:/var/lib/postgresql/data
    #Scripts
    - ./db-scripts:/scripts
    - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

    backend:
        image: node:12.16.1-alpine
        volumes:
            - .:/ws
        ports:
            - 3000:3000
        working_dir: /ws/backend
        entrypoint: sh -c 'tail -f'
    
